spring:
  profiles:
    active: dev
    
--- 
#spring的配置
spring:
  profiles: dev
  application:
    name: cloud-eureka
server:
  port: 8081
#eureka的配置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    registry-with-eureka:false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
   
---
#spring的配置
spring:
  profiles: test
  application:
    name: cloud-eureka
server:
  port: 8081
#eureka的配置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    registry-with-eureka:false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  
