spring:
  profiles:
  active: dev
  
---
server:
  port: 8082
  
#spring的配置
spring:
  profiles: dev
  application:
    name: cloud-service
    
#eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: springcloud-service-8082

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
            
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
feign:
  httpclient:
    connection-timeout: 5000
    
#info配置
info:
  app.name: springcloud-demo
  company.name: yincf
    
---
server:
  port: 8082
  
#spring的配置
spring:
  profiles: test
  application:
    name: cloud-service
    
#eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: springcloud-service-8082

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
            
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
feign:
  httpclient:
    connection-timeout: 5000
    
#info配置
info:
  app.name: springcloud-demo
  company.name: yincf
